export const UI_START_LOADING = 'UI_START_LOADING'
export const UI_STOP_LOADING = 'UI_STOP_LOADING'
export const SET_FORM_TEMPLATES = 'SET_FORM_TEMPLATES'
export const SORT_ASENDING = "SORT_ASENDING"
export const SORT_DESCENDING = "SORT_DESCENDING"
export const RESET_DEFAULT_SORT = "RESET_DEFAULT_SORT"