export const dummy = [
  {
    category: Array(2),
    created: "2021-06-05T14:06:35.271507",
    description: "exercitation fugiat incididunt proident, Lorem",
    link: "https://formpl.us/templates",
    name: "veniam, aliqua.",
  },
  {
    category: Array(3),
    created: "2021-06-05T14:06:36.765714",
    description: "cupidatat exercitation labore fugiat consequat.",
    link: "https://formpl.us/templates",
    name: "culpa fugiat laborum.",
  },
  {
    category: Array(3),
    created: "2021-06-05T14:06:37.147521",
    description: "tempor proident, aliquip nulla velit",
    link: "https://formpl.us/templates",
    name: "ipsum adipiscing minim",
  },
  {
    category: Array(3),
    created: "2021-06-05T14:06:36.968459",
    description: "cupidatat reprehenderit laborum. consectetur incididunt",
    link: "https://formpl.us/templates",
    name: "cupidatat aliqua. deserunt",
  },
  {
    category: Array(3),
    created: "2021-06-05T14:06:36.770685",
    description: "proident, reprehenderit minim labore incididunt",
    link: "https://formpl.us/templates",
    name: "amet, labore laborum.",
  },
  {
    category: Array(2),
    created: "2021-06-05T14:06:35.260740",
    description: "magna ipsum nostrud tempor cillum",
    link: "https://formpl.us/templates",
    name: "Lorem aliqua.",
  },
  {
    category: Array(3),
    created: "2021-06-05T14:06:36.967330",
    description: "Lorem consectetur velit elit, cillum",
    link: "https://formpl.us/templates",
    name: "laborum. consectetur nulla",
  },
  {
    category: Array(3),
    created: "2021-06-05T14:06:37.069271",
    description: "pariatur. cillum nulla dolor irure",
    link: "https://formpl.us/templates",
    name: "mollit dolor culpa",
  },
  {
    category: Array(3),
    created: "2021-06-05T14:06:36.463865",
    description: "pariatur. amet, aliquip nostrud laborum.",
    link: "https://formpl.us/templates",
    name: "nostrud exercitation dolor",
  },
  {
    category: Array(3),
    created: "2021-06-05T14:06:36.955622",
    description: "incididunt proident, dolor nostrud ullamco",
    link: "https://formpl.us/templates",
    name: "Lorem proident, dolor",
  },
  {
    category: Array(3),
    created: "2021-06-05T14:06:37.143727",
    description: "consectetur fugiat magna ipsum occaecat",
    link: "https://formpl.us/templates",
    name: "consequat. reprehenderit ipsum",
  },
  {
    category: Array(3),
    created: "2021-06-05T14:06:36.550123",
    description: "velit consequat. Excepteur occaecat deserunt",
    link: "https://formpl.us/templates",
    name: "culpa magna reprehenderit",
  },
  {
    category: Array(3),
    created: "2021-06-05T14:06:36.267469",
    description: "adipiscing fugiat aliqua. elit, pariatur.",
    link: "https://formpl.us/templates",
    name: "dolore magna tempor",
  },
  {
    category: Array(3),
    created: "2021-06-05T14:06:36.658445",
    description: "elit, officia incididunt laborum. occaecat",
    link: "https://formpl.us/templates",
    name: "elit, consequat. mollit",
  },
]
