export const UI_START_LOADING = "UI_START_LOADING"
export const UI_STOP_LOADING = "UI_STOP_LOADING"

export const SET_FORM_TEMPLATES = "GET_FORM_TEMPLATES"
export const FILTER_FORM_TEMPLATES = "FILTER_FORM_TEMPLATES"
export const RESET_FORM_TEMPLATES = "RESET_FORM_TEMPLATES"
